- name: "[BASE PKGS]     | Ensure that general desktop applications present"
  dnf: name={{item}}
  with_items:
   - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-26.noarch.rpm
   - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-26.noarch.rpm
   - transmission
   - vlc
   - kodi  
   - gparted
   - calibre
   - remmina  
   - gimp
   - unar
   - steam
   - easy-rsa
