- name: "[BASE PKGS]     | Ensure that general desktop applications present"
  dnf:
   disable_gpg_check: yes
   name:
    - https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2020.03.04-1.fedora.x86_64.rpm
    - https://github.com/kaikramer/keystore-explorer/releases/download/v5.4.4/kse-5.4.4-1.noarch.rpm
    - transmission
    - gparted
    - calibre
    - remmina
    - gimp
    - unar
    - easy-rsa
    - wine
    - p7zip
    - unetbootin
    - pdfshuffler
    - fuse-sshfs
    - nethogs

- name: Add the flathub flatpak repository remote to the system installation
  flatpak_remote:
   name: flathub
   state: present
   flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
   method: system

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
   name: flathub
   state: present
   flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
   method: user

- name: Install flatpak apps
  flatpak:
   name: "{{ item }}"
   state: present
  become: no
  with_items:
   - com.valvesoftware.Steam
   - org.videolan.VLC
   - org.openstreetmap.josm
   - org.gnome.FileRoller
