- name: "dnf | ensure Google chrome repo present"
  copy: src=google-chrome.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: "dnf | ensure Google chrome present"
  dnf: name=google-chrome-stable


- name: "install the rpmfusion repo packages"
  dnf: name={{ item }} state=present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-25.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-25.noarch.rpm

- name: "dnf | ensure Transmission present"
  dnf: name={{item}}
  with_items:
   - transmission
   - vlc

- name: "dnf | ensure stuff for thefuck present"
  dnf: name={{item}}
  with_items:
   - redhat-rpm-config
   - python2-devel
