#- name: "[Authy]          | Checking that Authy is installed"
#  stat:
#    path: /var/lib/snapd/snap/authy/current/authy
#  register: authy_installed
#
# - name: "[Authy]          | Install Authy with snap"
#  when: authy_installed.stat.exists == False
#  command:
#    cmd: snap install authy --beta
#
#- name: "[Authy]          | Install Authy icon"
#  copy: src=authy/authy.desktop
#    dest=/home/vilmosnagy/.local/share/applications/authy.desktop
#    owner=vilmosnagy group=vilmosnagy mode=0644
