- name: "[BASE APPS]     | Installing usefull applications"
  dnf: name={{item}}
  with_items:
   - vim
   - htop
   - pandoc

- name: "[BASE PKGS]     | Installing platform dependent necessary packages"
  dnf: name="{{item}}"
  with_items:
  - libselinux-python
