- name: "[HEROKU]      | Download package"
  unarchive:
    src: https://cli-assets.heroku.com/branches/stable/heroku-linux-amd64.tar.gz
    dest: /usr/local/lib
    remote_src: yes

- name: "[HEROKU]      | Create symlink"
  file:
    dest: /usr/local/bin/heroku
    src: /usr/local/lib/heroku/bin/heroku
    state: link

