# - include: install-docker-dnf.yml
#   when: ansible_pkg_mgr == 'dnf'

# - name: "[DOCKER]        | Installing Docker compose"
#  pip:
#   name: docker-compose

#- name: "[DOCKER]        | Create docker group"
#  group:
#    name: docker
#    state: present
#
#- name: "[DOCKER]        | Adding user vilmosnagy to Docker group"
#  user:
#    name: vilmosnagy
#    groups:
#      - docker
#    append: yes
#
#- name: "[DOCKER]        | Enable Docker service to start on boot"
#  systemd:
#   name: docker.service
#   enabled: yes
