- name: "[CAMUNDA]    | Checking that Camunda-Modeler is installed"
  stat:
    path: /opt/camunda-modeler
  register: camunda_modeler_installed

- name: "[CAMUNDA]    | Download Camunda Modeler"
  when: camunda_modeler_installed.stat.exists == False
  unarchive:
    src: https://camunda.org/release/camunda-modeler/1.16.2/camunda-modeler-1.16.2-linux-x64.tar.gz
    dest: /opt/
    remote_src: yes

- name: "[CAMUNDA]    | Install Camunda icon"
  when: camunda_modeler_installed.stat.exists == False
  copy: src=camunda-modeler/camunda-modeler.desktop
    dest=/home/vilmosnagy/.local/share/applications/camunda-modeler.desktop
    owner=vilmosnagy group=vilmosnagy mode=0644

- name: "[CAMUNDA]    | Checking that Camunda-Transactions plugin is installed"
  stat:
    path: /opt/camunda-modeler/plugins/bpmn-js-plugin-transaction-boundaries
  register: camunda_modeler_transactions_plugin_installed

- name: "[CAMUNDA]    | Download Camunda-Transactions plugin"
  when: camunda_modeler_transactions_plugin_installed.stat.exists == False
  git:
    repo: https://github.com/camunda/camunda-modeler-plugins.git
    dest: /tmp/camunda-plugins

- name: "[CAMUNDA]    | Copy Camunda-Transactions plugin to correct place"
  when: camunda_modeler_transactions_plugin_installed.stat.exists == False
  copy:
    src: /tmp/camunda-plugins/bpmn-js-plugin-transaction-boundaries
    dest: /opt/camunda-modeler/plugins/bpmn-js-plugin-transaction-boundaries
    owner: vilmosnagy
    group: vilmosnagy
    mode: 0644


- name: "[CAMUNDA]    | Checking that Camunda-TokenSimulation plugin is installed"
  stat:
    path: /opt/camunda-modeler/plugins/bpmn-js-token-simulation-plugin
  register: camunda_modeler_transactions_plugin_installed

- name: "[CAMUNDA]    | Download Camunda-TokenSimulation plugin"
  when: camunda_modeler_transactions_plugin_installed.stat.exists == False
  git:
    repo: https://github.com/philippfromme/bpmn-js-token-simulation-plugin.git
    dest: /tmp/bpmn-js-token-simulation-plugin

- name: "[CAMUNDA]    | Copy Camunda-TokenSimulation plugin to correct place"
  when: camunda_modeler_transactions_plugin_installed.stat.exists == False
  copy:
    src: /tmp/bpmn-js-token-simulation-plugin
    dest: /opt/camunda-modeler/plugins/bpmn-js-token-simulation-plugin
    owner: vilmosnagy
    group: vilmosnagy
    mode: 0644
