# TODO
- name: install the SOPS rpm from a remote repo
  dnf:
    name: 'https://github.com/getsops/sops/releases/download/v3.8.1/sops-3.8.1.x86_64.rpm'
    state: present
    disable_gpg_check: true
  when:
    - ansible_pkg_mgr == 'dnf'
