- name: "[YARN REPO]   | Ensure YARN repo present"
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: "[YARN]        | Installing yarn"
  dnf: name={{item}}
  with_items:
   - yarn