# TODO
- name: install the SOPS rpm from a remote repo
  dnf:
    name: 'https://github.com/getsops/sops/releases/download/v3.11.0/sops-3.11.0.x86_64.rpm'
    state: present
    disable_gpg_check: true
  when:
    - ansible_pkg_mgr == 'dnf'

- name: install the SOPS deb from a remote repo
  apt:
    deb: 'https://github.com/getsops/sops/releases/download/v3.11.0/sops_3.11.0_amd64.deb'
    state: present
  when:
    - ansible_pkg_mgr == 'apt'
