- include_tasks: install-dotnet.yml
- include_tasks: install-vscode.yml

- include_tasks: main-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- include_tasks: main-apt.yml
  when: ansible_pkg_mgr == 'apt'

- include_tasks: install-docker.yml
- include_tasks: install-npm-packages.yml
- include_tasks: install-dbschema.yml
- include_tasks: install-intellij.yml
- include_tasks: install-postman.yml
- include_tasks: install-soapui.yml
- include_tasks: install-kubectl.yml
- include_tasks: install-rclone.yml
- include_tasks: install-minikube.yml
- include_tasks: install-k3d.yml
- include_tasks: install-argo.yml
- include_tasks: install-helm.yml
- include_tasks: install-terraform.yml
- include_tasks: install-packer.yml
- include_tasks: install-gcloud.yml
- include_tasks: install-azure.yml
#- include_tasks: install-camunda-modeler.yml
- include_tasks: install-pip-packages.yml
- include_tasks: install-starship-shell.yml
- include_tasks: config-git-hooks.yml
- include_tasks: install-k9s.yml
