- include: install-dotnet.yml
- include: install-vscode.yml

- include: main-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- include: main-apt.yml
  when: ansible_pkg_mgr == 'apt'

- include: install-docker.yml
- include: install-npm-packages.yml
- include: install-dbschema.yml
- include: install-intellij.yml
- include: install-postman.yml
- include: install-soapui.yml
- include: install-kubectl.yml
- include: install-minikube.yml
- include: install-helm.yml
- include: install-terraform.yml
- include: install-packer.yml
- include: install-heroku.yml
- include: install-camunda-modeler.yml
- include: install-pip-packages.yml
- include: config-git-hooks.yml
