
- include: main-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- include: thermostat-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- include: install-docker.yml
- include: install-dbschema.yml

- include: install-intellij.yml
