- include: install-dotnet.yml

- include: main-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- include: install-docker.yml
- include: install-npm-packages.yml
- include: install-dbschema.yml
- include: install-intellij.yml
- include: config-git-hooks.yml

- pip:
    name: awslogs
