# TODO
# - include: install-yarn-dnf.yml

- name: "[BASE PKGS]     | Installing general development tools"
  dnf: name={{item}}
  with_items:
   - git
   - gitk
   - maven  
   - meld
   - VirtualBox
   - java-1.8.0-openjdk-src
   - android-tools
   - golang
   - npm
   - python-devel
   - openldap-devel
